name: Pages

on:
    push:
        branches:
            - main

jobs:
    publish_pages:
        name: Build and Publish Docs
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - uses: pnpm/action-setup@v2.0.1
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: Install Library Deps
              run: pnpm i

            - name: Install Docs Deps
              working-directory: ./docs
              run: pnpm i

            - name: Build
              working-directory: ./docs
              run: pnpm build

            - name: Push
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: pages
                  FOLDER: ./docs/build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SKIP_EMPTY_COMMITS: true
                  MESSAGE: "Build: ({sha}) {msg}"
