name: Publish Dev

on:
    push:
        branches:
            - development

jobs:
    publish_dev:
        name: Publish to dist Branch
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
                  registry-url: "https://registry.npmjs.org"

            - uses: pnpm/action-setup@v2.0.1
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: Install Deps
              run: pnpm i

            - name: Test
              run: pnpm t

            - name: Build
              run: pnpm build

            - name: Move Files
              run: |
                  mkdir build
                  mv dist build/dist
                  cp {LICENSE,README.md,package.json} build

            - name: Push
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist
                  FOLDER: ./build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SKIP_EMPTY_COMMITS: true
                  MESSAGE: "Build: ({sha}) {msg}"
